### ISSUE TITLE
concat layer axis=-1

### ISSUE THREAD

**Issue by skaae** [benanne/Lasagne#102] opened 2015-01-18 00:05 UTC
if you give concat layer axis=-1 it seems that the concatenate layer stacks the layers.

I concatenated two inputs of shape (64,20,1) with axis=-1 and got an output of (2,64,20,1)
but get_output_shape says that the output shape is (64,20,2), which is what I would expect.

**Comment by benanne** [comment] 2015-01-18 00:19
This is probably because it uses a custom implementation of `theano.tensor.concatenate`. It does this because the Theano implementation does not have a GPU version of the gradient, which makes it very slow. But it might not support `axis=-1` properly. I'll have a look at it soon.

**Comment by skaae** [comment] 2015-01-18 00:23
maybe just put an assert? It took me sometime to figure out what was going on.

**Comment by benanne** [comment] 2015-01-18 00:26
I think it would be better to support everything the original implementation supports :) Anyway, I'll see if I can look at it tomorrow.

**Comment by f0k** [comment] 2015-01-18 23:47
I think you'd just need to add the following at [the beginning of `utils.concatenate()`](https://github.com/benanne/Lasagne/blob/master/lasagne/utils.py#L91):
```python
if axis < 0:
    axis += tensor_list[0].ndim
```
The tests should be extended to cover that case as well. Please feel free to send us a pull request if you have the time.

(How difficult would it be to fix `theano.tensor.concatenate` instead of providing a workaround?)

**Comment by benanne** [comment] 2015-01-19 00:04
I believe theano.tensor.concatenate is fixed with the new GPUArray backend, so it would just have to be backported. The problem is that `GpuSplit` (needed for the gradient) does not exist. See also: https://groups.google.com/forum/#!searchin/theano-users/GpuSplit/theano-users/ZDuZkFvnEfI/eNe-NuZJibMJ

**Comment by skaae** [comment] 2015-01-19 09:46
I will send a pull request later today.

**Comment by f0k** [comment] 2015-01-19 11:01
> I will send a pull request later today.

Please have a look into whether you feel comfortable to fix this upstream in Theano instead, it seems it's not much more work. Citing Fred from the thread mentioned by @benanne:

> GpuSplit was done for the new GPU back-end, but not ported.

> It is easy to port. The code is in python only. You can look at sandbox/gpuarray/basic_ops.py, check the class GpuSplit. Copy it to sandbox/cuda/basic_ops.py and change it to not use GpuArrayType and not use as_gpuarray_variable. You will then just need an optimization to swap the CPU version with the GPU version. For an example, you can look at cuda/opt.py, the function local_gpu_dimshuffle_0.

> If you do it, it would be great to make a PR.

Basically you just need to define a class `GpuSplit` in `theano/sandbox/cuda/basic_ops.py` that derives from `theano.tensor.basic.Split` and override its `make_node()` method; everything else can be reused. Then add an optimizer to `theano/sandbox/cuda/opt.py` similar to the `local_gpu_dimshuffle_0` mentioned by Fred (just that it should replace `Split` by `GpuSplit`). If this is done, then Lasagne's `ConcatLayer` can just use `theano.tensor.concatenate`.

**Comment by skaae** [comment] 2015-01-19 11:04
I probably don’t :) But i’ll have a look at it.

**Comment by benanne** [comment] 2015-01-30 22:47
I added @f0k's suggested fix (https://github.com/benanne/Lasagne/issues/102#issuecomment-70432717). I was going to add a test for it and then realised that it would be wasted effort - once this is fixed in Theano this function goes in the bin anyway. Also I'm lazy.

**Closed** 2015-01-31 09:37 UTC
Labels: bug

**Comment by craffel** [comment] 2015-02-10 04:25
They merged my PR for `GpuSplit`:
https://github.com/Theano/Theano/pull/2482
@benanne Do you want to test that `T.concatenate` does what you want it to now?

**Comment by benanne** [comment] 2015-02-25 15:56
I just uploaded my local copy of Theano and it looks `Split` is not being replaced by `GpuSplit`:

```
>>> import theano
Using gpu device 0: GeForce GT 540M

>>> import theano.tensor as T
>>> import lasagne
>>> x = lasagne.utils.shared_empty(2)
>>> y = lasagne.utils.shared_empty(2)
>>> out = T.concatenate([x, y], axis=1)
>>> grad = T.grad(out.sum(), x)
>>> f = theano.function([], out)
>>> g = theano.function([], grad)

>>> theano.printing.debugprint(f)
HostFromGpu [@A] ''   1
 |GpuJoin [@B] ''   0
   |TensorConstant{1} [@C]
   |<CudaNdarrayType(float32, matrix)> [@D]
   |<CudaNdarrayType(float32, matrix)> [@E]

>>> theano.printing.debugprint(g)
GpuFromHost [@A] ''   7
 |Split{2}.0 [@B] ''   6
   |Alloc [@C] ''   5
   | |TensorConstant{(1, 1) of 1.0} [@D]
   | |Shape_i{0} [@E] ''   2
   | | |<CudaNdarrayType(float32, matrix)> [@F]
   | |Elemwise{Add}[(0, 0)] [@G] ''   4
   |   |Shape_i{1} [@H] ''   1
   |   | |<CudaNdarrayType(float32, matrix)> [@F]
   |   |Shape_i{1} [@I] ''   0
   |     |<CudaNdarrayType(float32, matrix)> [@J]
   |TensorConstant{1} [@K]
   |MakeVector [@L] ''   3
     |Shape_i{1} [@H] ''   1
     |Shape_i{1} [@I] ''   0
```

**Comment by craffel** [comment] 2015-02-25 16:11
Yours is different from mine.  I get 
```
>>> theano.printing.debugprint(g)
GpuSplit{2}.0 [@A] ''   6
 |GpuAlloc [@B] ''   5
 | |CudaNdarrayConstant{[[ 1.]]} [@C]
 | |Shape_i{0} [@D] ''   2
 | | |<CudaNdarrayType(float32, matrix)> [@E]
 | |Elemwise{Add}[(0, 0)] [@F] ''   4
 |   |Shape_i{1} [@G] ''   1
 |   | |<CudaNdarrayType(float32, matrix)> [@E]
 |   |Shape_i{1} [@H] ''   0
 |     |<CudaNdarrayType(float32, matrix)> [@I]
 |TensorConstant{1} [@J]
 |MakeVector [@K] ''   3
   |Shape_i{1} [@G] ''   1
   |Shape_i{1} [@H] ''   0
```

Not sure why.  Can you double check your installed version of Theano has `GpuSplit`?

**Comment by benanne** [comment] 2015-02-25 16:23
This is really strange. `theano.sandbox.cuda.basic_ops.GpuSplit` and `theano.sandbox.cuda.opt.local_gpu_split` are both there, but for some reason the optimization is not being applied. Clearing the Theano cache doesn't help either.

This is all on my laptop, I'll try on another machine when there is one available.

**Comment by craffel** [comment] 2015-02-25 16:27
K.  You can also try running this test: https://github.com/craffel/Theano/blob/c0d3bff3e319afe4950c12d2839709c4686a8fdc/theano/sandbox/cuda/tests/test_opt.py#L294

**Comment by benanne** [comment] 2015-02-25 16:31
It passes. So now I have no idea what's going on :p

**Comment by craffel** [comment] 2015-02-25 16:32
Hah, bizarre, I don't know -- let me know if I can help.

**Comment by f0k** [comment] 2015-02-25 19:03
I'm seeing the same output as @benanne. No `GpuSplit`. And the test passes:
```
nosetests theano/sandbox/cuda/tests/test_opt.py:test_local_split
Using gpu device 0: GeForce GT 640
.
----------------------------------------------------------------------
Ran 1 test in 1.689s

OK
```
The test directly checks if an instantiated `Split` op is moved to the GPU, while Sander's example checks if the gradient of a `Concatenate` op is moved to the GPU. Maybe something is different in these two cases?

`<offtopic>`
Something else in @benanne's example struck me: `out` is on CPU, `grad` is on GPU (as you see from the outermost ops). Verified directly:
```In [12]: out.type
Out[12]: TensorType(float32, matrix)

In [13]: grad.type
Out[13]: CudaNdarrayType(float32, matrix)
```
Any idea why?
Ah, I see, it's because the gradient is wrt. `x`, which is a shared variable on GPU. Sorry for the noise.
`</offtopic>`

**Comment by f0k** [comment] 2015-02-25 19:11
Okay great, I think I found it: The version of the optimizer @craffel has still contains both if cases:
https://github.com/craffel/Theano/blob/c0d3bff3e319afe4950c12d2839709c4686a8fdc/theano/sandbox/cuda/opt.py#L304
The one in Theano only contains the first one because @nouiz just removed the other 22 hours ago:
https://github.com/Theano/Theano/commit/745f50f7ec99cbc6ba0649421e823c6fed774f91
We need to add a test case and convince Fred to pull it in again. @craffel, do you want me to do it or do it yourself?

**Comment by craffel** [comment] 2015-02-25 19:16
Ah, weird, I think this comment references why he did that: https://github.com/Theano/Theano/pull/2482#discussion_r24264584

But it looks like it's actually useful, yeah.  I saw your comment on the commit.  I wonder where it was crashing...

**Comment by lamblin** [comment] 2015-02-25 19:17
The fix will probably need to be different, as @nouiz's one was making other optimizations crash, with a case in Pylearn2.

**Comment by nouiz** [comment] 2015-02-25 20:07
Ok, I'll try to implement that original case in a good way.

**Comment by nouiz** [comment] 2015-02-25 20:33
Done in this PR:

https://github.com/Theano/Theano/pull/2533

**Comment by f0k** [comment] 2015-02-25 20:42
Thank you Fred, [it works](https://github.com/Theano/Theano/commit/745f50f7ec99cbc6ba0649421e823c6fed774f91#commitcomment-9922908)!

**Comment by craffel** [comment] 2015-02-25 20:56
Nice, thanks @nouiz!

**Comment by benanne** [comment] 2015-02-25 21:31
Awesome! that means we can get rid of `lasagne.utils.concatenate` I guess :) I'll try to do that tomorrow.
