### ISSUE TITLE
Is this some problem with Lasagne?

### ISSUE THREAD

**Issue by run2** [benanne/Lasagne#101] opened 2015-01-15 11:35 UTC
Hi - I am using lasagne and bleeding version of theano for quite some while. Then I had to make some changes in the lasagne code to have my own objective function. I made the change and this is the sequence of what happened 
1) To recompile lasagne (from git repo - that I had checked out at least 3 weeks back)
sudo python setup.py install

2) when I reran my code I suddenly found this error
The same cache key is associated to different modules (/home/debanjan/.theano/compiledir_Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmp4xhBVg/c07737f1d301ae23e9d459b32aa6f2b5.so and /home/debanjan/.theano/compiledir_Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpNmR1oX/57987abfa26302054d6be91525f69179.so). This is not supposed to happen! You may need to manually delete your cache directory to fix this.

3) Not knowing what exactly is going on, I removed all tmp* directories from 
~/.theano/compiledir_Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64

4) Then I reran the code and found this error
ImportError: cannot import name GpuCorrMM

5) Now, that meant the theano version was not the dev version any more. This was strange because before doing step 1) I had ran a pip freeze command which showed that the theano version was indeed the dev version installed from a checkedout git repository. When I ran pip freeze again at this point, it showed 0.6. 

6) Again - not knowing what exactly was going on I reinstalled theano from the local git theano repo
sudo python setup.py develop 

7) Now the pip freeze gave the right dev version on theano

8) Now when I ran the code, it ran but I am seeing a strange thing. I was checking running python processes and I saw a nvcc process along with my process.

nvcc -shared -O3 -use_fast_math -arch sm_30 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=f6d896860391dd5093b721c63a0b2b33,-D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC -Xlinker -rpath,/home/debanjan/.theano/compiledir_Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -Xlinker -rpath,/usr/local/cuda-6.5/lib -Xlinker -rpath,/usr/local/cuda-6.5/lib64 -I/home/debanjan/.theano/compiledir_Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -I/usr/local/cuda-6.5/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/home/debanjan/pythonrepos/Theano/theano/sandbox/cuda -o /home/debanjan/.theano/compiledir_Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpHBvlRW/259a64255e7ca2eaec3735380a7c8ef3.so mod.cu -L/home/debanjan/.theano/compiledir_Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -L/usr/lib -lpython2.7 -lcudart -lcublas -lcuda_ndarray

I am 100% sure this process did not run before when I used to run my code. Or, it ran and killed itself too soon for me to see if when I checked my process after starting it. Now it was there for long.
Obviously the process dies when I kill my process. And I am Ok with nvcc running under the hood to compile stuff. But why is it that it was not being invoked earlier.

As far as my code is concerned, apart from that change in Lasagne objectives I had not made any other change between two runs. I had not pulled lasagne or theano over the last 3 weeks.

Would be grateful to know if this is some issue or expected or something weird ?

I can re-create this problem, every time I update and re install lasagne

Regards

**Comment by benanne** [comment] 2015-01-15 12:35
It sounds like this may be the same issue as #89.

I don't understand why `python setup.py install` would install Theano 0.6, since we explicitly require a more recent version. Does anybody have any idea what's going on here?

**Comment by run2** [comment] 2015-01-15 12:43
Exactly - python setup.py install is installing  Theano 0.6

Previously I had 
-e git+https://github.com/Theano/Theano.git@ba45997f3d252f1a0674d93b1f073ba136521de2#egg=Theano-master
-e git+git@localhost:synapseobjcounter@80db53ac84d843885599c042b20e8b466bc6ae51#egg=Lasagne-master

Now I have
Lasagne==0.1dev
Theano==0.6.0
After running setup from relevant repos.

Do you know the thing with nvcc ? Is it alright ? or not alright ?

**Comment by benanne** [comment] 2015-01-15 12:47
It should have been invoked earlier as well, Theano always uses nvcc to compile a bunch of stuff. This stuff gets cached quite agressively though, so after the first run it should be considerably faster. Maybe that is why you didn't spot it before.

**Comment by run2** [comment] 2015-01-15 12:50
hmm - so may be it is because I removed all the cache after I had that first problem of same key in two cache files (which btw I could not figure out)

What is the way to make sure that my lasagne, nolearn and theano are exactly as needed (as far as versions as concerned). ?

**Comment by f0k** [comment] 2015-01-15 13:19
> I don't understand why `python setup.py install` would install Theano 0.6, since we explicitly require a more recent version. Does anybody have any idea what's going on here?

We don't require a particular version as far as `setup.py` is concerned, do we? https://github.com/benanne/Lasagne/blob/master/setup.py#L15 The `requirements.txt` file is only used by `pip`.

> What is the way to make sure that my lasagne, nolearn and theano are exactly as needed (as far as versions as concerned). ?

If you install everything in development mode (`sudo python setup.py develop` or `python setup.py develop --prefix=~/.local`) you just need to pull the changes into your checkouts and never run `setup.py` again. Nevertheless, Lasagne's installation shouldn't downgrade Theano, that needs to be fixed.

> Do you know the thing with nvcc ? Is it alright ? or not alright ?

I guess everything is alright. The first time after deleting Theano's compilation caches a lot of stuff has to be compiled anew, so there will be many `nvcc` processes, maybe some of them taking a bit longer.

**Comment by dnouri** [comment] 2015-01-15 13:56
On 01/15/2015 02:19 PM, Jan Schlüter wrote:
>     I don't understand why |python setup.py install| would install
>     Theano 0.6, since we explicitly require a more recent version. Does
>     anybody have any idea what's going on here?
> 
> We don't require a particular version as far as |setup.py| is concerned,
> do we? https://github.com/benanne/Lasagne/blob/master/setup.py#L15 The
> |requirements.txt| file is only used by |pip|.

The installation says: when installing from the source, run "pip install
-r requirements.txt" prior to running "python setup.py install", and
that seems to work just fine for me, and the second step will print:

  Best match: Theano 0.6.0
  Theano 0.6.0 is already the active version in easy-install.pth

A setup.py without any specific version should be just happy and not do
anything if any version of Theano is already installed.

That said, it's easy to be confused by this stuff, and pip/setuptools
are unfortunately a little buggy these days.

The reason we don't want the exact versions in setup.py is that this
would make installation of Lasagne with some custom versions of the
dependencies impossible.  Say at some point in the future you wanted to
use Theano 0.7 (we can still hope!) with the current version of Lasagne:
that'd be impossible if you made an exact pin of that into setup.py.

>     What is the way to make sure that my lasagne, nolearn and theano are
>     exactly as needed (as far as versions as concerned). ?
> 
> If you install everything in development mode (|sudo python setup.py
> develop| or |python setup.py develop --prefix=~/.local|) you just need
> to pull the changes into your checkouts and never run |setup.py| again.
> Nevertheless, Lasagne's installation shouldn't downgrade Theano, that
> needs to be fixed.

Yeah, it shouldn't.  And I don't think it's Lasagne's fault.

@run2, would you provide us with exact steps to reproduce this problem?
 Maybe inside a new virtualenv, so that it doesn't cross with anything
that you have installed system-wide.

**Comment by run2** [comment] 2015-01-15 17:00
Ah! see when I first installed lasagne - I installed it using requirements.txt . And that is why I got -e git+https://github.com/Theano/Theano.git@ba45997f3d252f1a0674d93b1f073ba136521de2#egg=Theano-master
because that is what is there in the requirements.txt

Long before that I had installed theano - by pip install.

Today, I did just an install on lasagne (after I changed some code) - without that requirements.txt . I gather I need not have done that install. But nevertheless - when I did that, it defaulted to 0.6 theano.  Does that make sense ?

Now - question is, if I now do
git clone git://github.com/Theano/Theano.git
and
cd Theano
python setup.py develop
How do I link lasagne to this version ?

Sorry I am a bit grainy on this

**Comment by dnouri** [comment] 2015-01-15 18:13
On 01/15/2015 06:00 PM, run2 wrote:
> Ah! see when I first installed lasagne - I installed it using
> requirements.txt . And that is why I got -e
> git+https://github.com/Theano/Theano.git@ba45997f3d252f1a0674d93b1f073ba136521de2#egg=Theano-master
> because that is what is there in the requirements.txt
> 
> Long before that I had installed theano - by pip install.
> 
> Today, I did just an install on lasagne (after I changed some code) -
> without that requirements.txt . I gather I need not have done that
> install. But nevertheless - when I did that, it defaulted to 0.6 theano.
> Does that make sense ?

"pip install Theano" shouldn't downgrade an existing Theano install.

If you do a "python setup.py install" or similar with Lasagne, then yes,
it'll use any existing Theano version (maybe the one you installed using
requirements.txt just before).  If there isn't any, it will download the
incompatible 0.6 release.  It's easy to get confused; best to get more
familiar with how pip and setuptools work.

> Now - question is, if I now do
> git clone git://github.com/Theano/Theano.git
> and
> cd Theano
> python setup.py develop
> How do I link lasagne to this version ?

This version of Theano will be installed with whatever Python you called
it with.  So if "python" here is your global Python's interpreter
(usually a bad idea, take a look at virtualenv), then using the same
"python" with Lasagne will do what you want.

Feel free to close this issue if you feel it can be.

**Closed** 2015-01-16 08:51 UTC

**Comment by MadMLScientist** [comment] 2015-08-26 07:38
Hello Daniel,
  When I run the code in Using convolutional neural nets to detect facial keypoints tutorial, an AttributeError occured saying that 'DenseLayer' has no attribute 'get_output'.So I go check the code
in lasagne,and found no method called 'get_output' in lasagne/layers/dense.py or base.py.
  I wonder if I missed some packages or installed lasagne in a wrong way, thx.

**Comment by benanne** [comment] 2015-08-26 09:09
`get_output()` was turned from a `Layer` method into a top-level function a while ago. It sounds like you may have an old version of nolearn that is still trying to call `get_output()` on a `Layer` class, but your (newer) version of Lasagne doesn't have this anymore.

**Comment by MadMLScientist** [comment] 2015-08-26 09:20
Problem just solved!You're right about the version,I uninstall nolearn and Lasagne then run
pip install -U -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt
and it worked.Besides, I use Anaconda.

**Comment by f0k** [comment] 2018-05-25 09:47
> i'm getting this error

Where and when do you get this error? What did you try to run? What's the backtrace?
